# Default apps
bind = SUPER, return, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER, R, exec, $menu

bind = SUPER, A, exec, $webapp="https://claude.ai"
bind = SUPER, Y, exec, $webapp="https://youtube.com"
bind = SUPER, D, exec, $webapp="https://discord.com/channels/@me"
bind = SUPER, T, exec, $webapp="https://twitch.tv"

bind = SUPER, Q, killactive,

# End active session
bind = SUPER, ESCAPE, exec, hyprlock
bind = SUPER SHIFT, ESCAPE, exec, systemctl suspend
bind = SUPER ALT, ESCAPE, exit,

# Control tiling
bind = SUPER, V, togglesplit,
bind = SUPER, P, pseudo,
bind = SUPER, space, exec, hyprctl --batch "dispatch togglefloating; dispatch centerwindow"

# Group tiling
bind = SUPER, G, togglegroup,
bind = SUPER, bracketleft, changegroupactive , b
bind = SUPER, bracketright, changegroupactive , f

# Worspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Magic workspace
bind = SUPER, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic

# Mouse resize window
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Swap window
bind = SUPER SHIFT, h, swapwindow, l
bind = SUPER SHIFT, l, swapwindow, r

# Move focus
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Audio
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
