# Monitors
monitor=,3440x1440@120,auto,auto

# Programs
$terminal = foot
$webapp = brave --new-window --ozone-platform=wayland --app
$fileManager = pcmanfm 
$menu = fuzzel

# Includes
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/configs/decoration.conf
source = ~/.config/hypr/configs/bindings.conf
source = ~/.config/hypr/configs/windows.conf

